version: 2.0
jobs:
  build:
    docker:
      - image: membrane/bionic-membrane:latest
    environment:
      MIX_ENV: test
    working_directory: '~/app'

    steps:
      - checkout
      - run: cd basic
      - run: mix deps.get
      - run: mix deps.compile --all
      - run: mix format --check-formatted
      - run: mix test
      - run: cd ../rtp
      - run: mix deps.get
      - run: mix deps.compile --all
      - run: mix format --check-formatted
      - run: mix test
