version: 2.0
jobs:
  build:
    docker:
      - image: membrane/bionic-membrane:latest
    environment:
      MIX_ENV: test
    working_directory: '~/app'

    steps:
      - checkout
      - run: cd basic && mix deps.get
      - run: cd basic && mix deps.compile --all
      - run: cd basic && mix format --check-formatted
      - run: cd basic && mix test
      - run: git submodule init && git submodule update
      - run: cd rtp && mix deps.get
      - run: cd rtp && mix deps.compile --all
      - run: cd rtp && mix format --check-formatted
      - run: cd rtp && mix test
